name: Apli internet
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: On déploie à gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Préparation de Node.js
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 16

      - name: Ouvrir la branche
        uses: actions/checkout@v2

      - name: Nétoyer les dépendances d'installation
        run: yarn install --frozen-lockfile

      - name: Déployer
        run: |
          git config user.name "julienmalard" && git config user.email "julien.malard@mail.mcgill.ca"
          yarn déployer
